services:
  dynamodb-local:
    build: .
    container_name: dynamodb-local
    ports:
      - "4567:4566"
    volumes:
      - dynamodb_data:/data
    networks:
      - dynamodb-network

volumes:
  dynamodb_data:

networks:
  dynamodb-network:
    driver: bridge
